name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        java: [8]
    steps:
      - uses: actions/checkout@v5
      - name: Setup java ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - run: mvn test -B
